---
Name: markdown
After: 'framework/*','cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs

DataObject:
  extensions:
    - MarkdownExtension

MarkdownCloudinaryUpload:
  enable: true

LeftAndMain:
  extensions:
    - MarkdownLeftAndMainExtension

Director:
  rules:
    'cloudinary-upload//$Action': 'MarkdownCloudinaryUpload_Controller'
